-- ============================================================
-- EXTENSIONES
-- ============================================================

create extension if not exists pgcrypto;


-- ============================================================
-- TABLA: preguntas
-- ============================================================

create table if not exists public.preguntas (
  id bigint generated by default as identity primary key,

  anio integer not null,
  asignatura text not null,

  enunciado text not null,

  opcion_1 text not null,
  opcion_2 text not null,
  opcion_3 text not null,
  opcion_4 text not null,

  respuesta_correcta smallint not null,

  created_at timestamptz not null default now(),

  constraint preguntas_anio_check
    check (anio >= 2000 and anio <= 2100),

  constraint preguntas_respuesta_correcta_check
    check (respuesta_correcta between 1 and 4)
);


create index if not exists preguntas_anio_idx
  on public.preguntas (anio);

create index if not exists preguntas_asignatura_idx
  on public.preguntas (asignatura);


-- ============================================================
-- TABLA: historial_fallos
-- ============================================================

create table if not exists public.historial_fallos (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  pregunta_id bigint not null
    references public.preguntas(id)
    on delete cascade,

  respuesta_usuario smallint not null,

  created_at timestamptz not null default now(),

  constraint historial_fallos_respuesta_check
    check (respuesta_usuario between 1 and 4)
);


create index if not exists historial_fallos_user_id_idx
  on public.historial_fallos (user_id);

create index if not exists historial_fallos_pregunta_id_idx
  on public.historial_fallos (pregunta_id);

create index if not exists historial_fallos_created_at_idx
  on public.historial_fallos (created_at desc);


-- ============================================================
-- RLS
-- ============================================================

alter table public.preguntas enable row level security;
alter table public.historial_fallos enable row level security;


-- ============================================================
-- POLICIES: preguntas
-- ============================================================

drop policy if exists "Usuarios autenticados pueden leer preguntas"
on public.preguntas;

create policy "Usuarios autenticados pueden leer preguntas"
on public.preguntas
for select
to authenticated
using (true);


-- ============================================================
-- POLICIES: historial de fallos
-- ============================================================

drop policy if exists "Usuarios pueden ver sus fallos"
on public.historial_fallos;

create policy "Usuarios pueden ver sus fallos"
on public.historial_fallos
for select
to authenticated
using (auth.uid() = user_id);


drop policy if exists "Usuarios pueden insertar sus fallos"
on public.historial_fallos;

create policy "Usuarios pueden insertar sus fallos"
on public.historial_fallos
for insert
to authenticated
with check (auth.uid() = user_id);


-- ============================================================
-- FUNCIÓN RPC: preguntas aleatorias
-- ============================================================

create or replace function public.obtener_preguntas_aleatorias(
  cantidad integer default 10
)
returns table (
  id bigint,
  anio integer,
  asignatura text,
  enunciado text,
  opcion_1 text,
  opcion_2 text,
  opcion_3 text,
  opcion_4 text,
  respuesta_correcta smallint,
  created_at timestamptz
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    p.id,
    p.anio,
    p.asignatura,
    p.enunciado,
    p.opcion_1,
    p.opcion_2,
    p.opcion_3,
    p.opcion_4,
    p.respuesta_correcta,
    p.created_at
  from public.preguntas p
  order by random()
  limit greatest(1, least(cantidad, 200));
$$;


-- ============================================================
-- FUNCIÓN RPC: corregir test
--
-- La corrección ocurre en PostgreSQL, no en el navegador.
-- ============================================================

create or replace function public.corregir_test(
  respuestas jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  resultado jsonb;
begin
  with respuestas_parseadas as (
    select
      (item->>'pregunta_id')::bigint as pregunta_id,
      nullif(item->>'respuesta', '')::smallint as respuesta
    from jsonb_array_elements(respuestas) as item
  ),
  correccion as (
    select
      rp.pregunta_id,
      rp.respuesta,
      p.respuesta_correcta
    from respuestas_parseadas rp
    inner join public.preguntas p
      on p.id = rp.pregunta_id
  ),
  totales as (
    select
      count(*) filter (
        where respuesta is not null
          and respuesta = respuesta_correcta
      ) as aciertos,

      count(*) filter (
        where respuesta is not null
          and respuesta <> respuesta_correcta
      ) as fallos,

      count(*) filter (
        where respuesta is null
      ) as blancas
    from correccion
  )
  select jsonb_build_object(
    'aciertos', aciertos,
    'fallos', fallos,
    'blancas', blancas,
    'puntuacion', (aciertos * 3) - fallos
  )
  into resultado
  from totales;

  return resultado;
end;
$$;


-- ============================================================
-- GRANTS RPC
-- ============================================================

revoke all on function public.obtener_preguntas_aleatorias(integer)
from public;

grant execute on function public.obtener_preguntas_aleatorias(integer)
to authenticated;

revoke all on function public.corregir_test(jsonb)
from public;

grant execute on function public.corregir_test(jsonb)
to authenticated;