-- ============================================================
-- MIGRACIÓN 002: Fase 2 — Motor de exámenes completo
-- ============================================================


-- ============================================================
-- TABLA: sesiones_estudio
-- Historial de tests completados por el usuario
-- ============================================================

create table if not exists public.sesiones_estudio (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  modo text not null
    check (modo in ('rapido', 'asignatura', 'oficial', 'fallos')),

  asignatura text,            -- null cuando modo != 'asignatura'
  total_preguntas integer not null,
  aciertos integer not null,
  fallos integer not null,
  blancas integer not null,
  puntuacion integer not null,

  created_at timestamptz not null default now()
);

create index if not exists sesiones_user_id_idx
  on public.sesiones_estudio (user_id);

create index if not exists sesiones_created_at_idx
  on public.sesiones_estudio (created_at desc);


-- ============================================================
-- RLS: sesiones_estudio
-- ============================================================

alter table public.sesiones_estudio enable row level security;

drop policy if exists "Usuarios pueden ver sus sesiones"
on public.sesiones_estudio;

create policy "Usuarios pueden ver sus sesiones"
on public.sesiones_estudio
for select
to authenticated
using (auth.uid() = user_id);


drop policy if exists "Usuarios pueden insertar sus sesiones"
on public.sesiones_estudio;

create policy "Usuarios pueden insertar sus sesiones"
on public.sesiones_estudio
for insert
to authenticated
with check (auth.uid() = user_id);


-- ============================================================
-- FUNCIÓN RPC: preguntas por asignatura
-- ============================================================

create or replace function public.obtener_preguntas_por_asignatura(
  p_asignatura text,
  cantidad integer default 20
)
returns table (
  id bigint,
  anio integer,
  asignatura text,
  enunciado text,
  opcion_1 text,
  opcion_2 text,
  opcion_3 text,
  opcion_4 text,
  respuesta_correcta smallint,
  created_at timestamptz
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    p.id, p.anio, p.asignatura, p.enunciado,
    p.opcion_1, p.opcion_2, p.opcion_3, p.opcion_4,
    p.respuesta_correcta, p.created_at
  from public.preguntas p
  where p.asignatura = p_asignatura
  order by random()
  limit greatest(1, least(cantidad, 200));
$$;


-- ============================================================
-- FUNCIÓN RPC: preguntas de la Caja de Fallos del usuario
-- ============================================================

create or replace function public.obtener_preguntas_de_fallos(
  p_user_id uuid,
  cantidad integer default 20
)
returns table (
  id bigint,
  anio integer,
  asignatura text,
  enunciado text,
  opcion_1 text,
  opcion_2 text,
  opcion_3 text,
  opcion_4 text,
  respuesta_correcta smallint,
  created_at timestamptz,
  veces_fallada bigint
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    p.id, p.anio, p.asignatura, p.enunciado,
    p.opcion_1, p.opcion_2, p.opcion_3, p.opcion_4,
    p.respuesta_correcta, p.created_at,
    count(hf.id) as veces_fallada
  from public.historial_fallos hf
  inner join public.preguntas p on p.id = hf.pregunta_id
  where hf.user_id = p_user_id
  group by p.id
  order by veces_fallada desc, random()
  limit greatest(1, least(cantidad, 200));
$$;


-- ============================================================
-- FUNCIÓN RPC: listado de asignaturas disponibles
-- ============================================================

create or replace function public.obtener_asignaturas()
returns table (asignatura text, total bigint)
language sql
stable
security invoker
set search_path = public
as $$
  select asignatura, count(*) as total
  from public.preguntas
  group by asignatura
  order by asignatura;
$$;


-- ============================================================
-- FUNCIÓN RPC: resumen de fallos del usuario (para /fallos)
-- ============================================================

create or replace function public.obtener_resumen_fallos(
  p_user_id uuid
)
returns table (
  pregunta_id bigint,
  enunciado text,
  asignatura text,
  veces_fallada bigint,
  ultima_vez timestamptz
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    p.id as pregunta_id,
    p.enunciado,
    p.asignatura,
    count(hf.id) as veces_fallada,
    max(hf.created_at) as ultima_vez
  from public.historial_fallos hf
  inner join public.preguntas p on p.id = hf.pregunta_id
  where hf.user_id = p_user_id
  group by p.id, p.enunciado, p.asignatura
  order by veces_fallada desc, ultima_vez desc;
$$;


-- ============================================================
-- GRANTS nuevas RPCs
-- ============================================================

revoke all on function public.obtener_preguntas_por_asignatura(text, integer) from public;
grant execute on function public.obtener_preguntas_por_asignatura(text, integer) to authenticated;

revoke all on function public.obtener_preguntas_de_fallos(uuid, integer) from public;
grant execute on function public.obtener_preguntas_de_fallos(uuid, integer) to authenticated;

revoke all on function public.obtener_asignaturas() from public;
grant execute on function public.obtener_asignaturas() to authenticated;

revoke all on function public.obtener_resumen_fallos(uuid) from public;
grant execute on function public.obtener_resumen_fallos(uuid) to authenticated;
