-- ============================================================
-- MIGRACIÓN 003: Flashcards con algoritmo SM-2
-- ============================================================


-- ============================================================
-- TABLA: flashcards
-- ============================================================

create table if not exists public.flashcards (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  -- Contenido
  frente text not null,
  dorso  text not null,
  asignatura text not null default 'General',

  -- Algoritmo SM-2
  intervalo    integer  not null default 1,      -- días hasta siguiente repaso
  facilidad    numeric  not null default 2.5,    -- factor de facilidad (EF)
  repeticiones integer  not null default 0,      -- número de repasos correctos consecutivos
  proxima_vez  date     not null default current_date,  -- fecha del siguiente repaso

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists flashcards_user_id_idx
  on public.flashcards (user_id);

create index if not exists flashcards_proxima_vez_idx
  on public.flashcards (user_id, proxima_vez);


-- ============================================================
-- RLS: flashcards
-- ============================================================

alter table public.flashcards enable row level security;

drop policy if exists "Usuarios pueden ver sus flashcards" on public.flashcards;
create policy "Usuarios pueden ver sus flashcards"
on public.flashcards for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Usuarios pueden insertar flashcards" on public.flashcards;
create policy "Usuarios pueden insertar flashcards"
on public.flashcards for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Usuarios pueden actualizar sus flashcards" on public.flashcards;
create policy "Usuarios pueden actualizar sus flashcards"
on public.flashcards for update to authenticated
using (auth.uid() = user_id);

drop policy if exists "Usuarios pueden borrar sus flashcards" on public.flashcards;
create policy "Usuarios pueden borrar sus flashcards"
on public.flashcards for delete to authenticated
using (auth.uid() = user_id);


-- ============================================================
-- FUNCIÓN RPC: flashcards pendientes de hoy
-- ============================================================

create or replace function public.obtener_flashcards_pendientes(
  p_user_id uuid,
  cantidad integer default 20
)
returns table (
  id bigint,
  frente text,
  dorso text,
  asignatura text,
  intervalo integer,
  facilidad numeric,
  repeticiones integer,
  proxima_vez date,
  created_at timestamptz,
  updated_at timestamptz
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    f.id, f.frente, f.dorso, f.asignatura,
    f.intervalo, f.facilidad, f.repeticiones, f.proxima_vez,
    f.created_at, f.updated_at
  from public.flashcards f
  where f.user_id = p_user_id
    and f.proxima_vez <= current_date
  order by f.proxima_vez asc
  limit greatest(1, least(cantidad, 200));
$$;

revoke all on function public.obtener_flashcards_pendientes(uuid, integer) from public;
grant execute on function public.obtener_flashcards_pendientes(uuid, integer) to authenticated;


-- ============================================================
-- TABLA: rachas (racha de días de estudio)
-- ============================================================

create table if not exists public.rachas (
  user_id uuid primary key
    references auth.users(id)
    on delete cascade,

  racha_actual   integer  not null default 0,
  racha_maxima   integer  not null default 0,
  ultimo_estudio date,

  updated_at timestamptz not null default now()
);

alter table public.rachas enable row level security;

drop policy if exists "Usuarios pueden ver su racha" on public.rachas;
create policy "Usuarios pueden ver su racha"
on public.rachas for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Usuarios pueden upsert su racha" on public.rachas;
create policy "Usuarios pueden upsert su racha"
on public.rachas for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);


-- ============================================================
-- FUNCIÓN RPC: registrar actividad diaria (upsert racha)
-- ============================================================

create or replace function public.registrar_actividad()
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_hoy     date := current_date;
  v_racha   public.rachas%rowtype;
begin
  select * into v_racha from public.rachas where user_id = v_user_id;

  if not found then
    insert into public.rachas (user_id, racha_actual, racha_maxima, ultimo_estudio)
    values (v_user_id, 1, 1, v_hoy);
    return;
  end if;

  -- Ya estudió hoy → no hacer nada
  if v_racha.ultimo_estudio = v_hoy then
    return;
  end if;

  -- Estudió ayer → extender racha
  if v_racha.ultimo_estudio = v_hoy - 1 then
    update public.rachas set
      racha_actual   = v_racha.racha_actual + 1,
      racha_maxima   = greatest(v_racha.racha_maxima, v_racha.racha_actual + 1),
      ultimo_estudio = v_hoy,
      updated_at     = now()
    where user_id = v_user_id;
  else
    -- Racha rota → reiniciar
    update public.rachas set
      racha_actual   = 1,
      ultimo_estudio = v_hoy,
      updated_at     = now()
    where user_id = v_user_id;
  end if;
end;
$$;

revoke all on function public.registrar_actividad() from public;
grant execute on function public.registrar_actividad() to authenticated;
