-- ============================================================
-- MIGRACIÓN 004: Panel de Pareja
-- ============================================================


-- ============================================================
-- TABLA: hitos_pareja
-- Hitos y logros de la opositora, visibles desde el panel pareja
-- ============================================================

create table if not exists public.hitos_pareja (
  id bigint generated by default as identity primary key,

  -- La opositora es la que añade hitos sobre sí misma
  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  titulo      text not null,
  descripcion text,
  emoji       text not null default '🏆',
  desbloqueado boolean not null default false,
  fecha_desbloqueo date,

  created_at timestamptz not null default now()
);

create index if not exists hitos_user_id_idx
  on public.hitos_pareja (user_id);


-- ============================================================
-- TABLA: nota_pareja
-- Una única nota de ánimo que la pareja puede ver
-- ============================================================

create table if not exists public.nota_pareja (
  user_id uuid primary key
    references auth.users(id)
    on delete cascade,

  contenido text not null default '',
  updated_at timestamptz not null default now()
);


-- ============================================================
-- RLS
-- ============================================================

alter table public.hitos_pareja enable row level security;
alter table public.nota_pareja  enable row level security;

-- hitos_pareja: la opositora puede ver y gestionar los suyos
drop policy if exists "Usuarios pueden gestionar sus hitos" on public.hitos_pareja;
create policy "Usuarios pueden gestionar sus hitos"
on public.hitos_pareja for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- nota_pareja: la opositora puede gestionar la suya
drop policy if exists "Usuarios pueden gestionar su nota" on public.nota_pareja;
create policy "Usuarios pueden gestionar su nota"
on public.nota_pareja for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);


-- ============================================================
-- Hitos predeterminados (se insertan al usar la función)
-- ============================================================

create or replace function public.inicializar_hitos_pareja(p_user_id uuid)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  -- Sólo insertar si no tiene hitos ya
  if exists (select 1 from public.hitos_pareja where user_id = p_user_id) then
    return;
  end if;

  insert into public.hitos_pareja (user_id, titulo, descripcion, emoji, desbloqueado)
  values
    (p_user_id, 'Primer simulacro',        'Completar el primer test completo',         '🎯', false),
    (p_user_id, 'Racha de 7 días',          'Estudiar 7 días seguidos',                  '🔥', false),
    (p_user_id, 'Racha de 30 días',         'Estudiar 30 días seguidos',                 '🌟', false),
    (p_user_id, '100 flashcards creadas',   'Crear al menos 100 tarjetas en el mazo',    '🃏', false),
    (p_user_id, 'Cero fallos en un test',   'Completar un test sin ningún error',        '💎', false),
    (p_user_id, 'Top 3 materias repasadas', 'Practicar más de 3 asignaturas distintas',  '📚', false),
    (p_user_id, 'Simulacro oficial 200Q',   'Completar el simulacro oficial completo',   '🏆', false),
    (p_user_id, 'Primera racha',            'Estudiar 3 días consecutivos',              '✨', false);
end;
$$;

revoke all on function public.inicializar_hitos_pareja(uuid) from public;
grant execute on function public.inicializar_hitos_pareja(uuid) to authenticated;
